version: '3.3'

services:
   db:
     image: mysql:5.7
     command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
     volumes:
         - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
     environment:
       MYSQL_ROOT_PASSWORD: local

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8080:80"
     #disable_ipv6: 'true'
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: local
       WORDPRESS_DB_NAME: primary
   
   wordpress2:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "9091:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: local1
       WORDPRESS_DB_PASSWORD: local
       WORDPRESS_DB_NAME: secondary

volumes:
  db_data:
  db_data2:
